apiVersion: template.openshift.io/v1
kind: Template
metadata:
  name: rose-service-template
objects:
- apiVersion: v1
  kind: Service
  labels:
    labels:
      kubevirt.io/domain: ${NAME}
  metadata:
    name: ${NAME}
  spec:
    ports:
      - name: ssh
        port: 22
      - name: http
        port: 80
      - name: https
        port: 443
      - name: rdp
        port: 3389
      - name: rdp-alt
        port: 3390
        targetPort: 3389
    selector:
      kubevirt.io/domain: ${NAME}
    type: LoadBalancer
parameters:
- description: Name for the new VM
  name: NAME
  required: true
