apiVersion: template.openshift.io/v1
kind: Template
metadata:
  annotations:
    iconClass: icon-centos
    name.os.template.kubevirt.io/centos8: CentOS 8 or higher
    template.kubevirt.io/provider: Red Hat Virtual ROSE
    template.kubevirt.ui/parent-provider: Red Hat
    template.kubevirt.ui/parent-provider-url: https://www.centos.org
    template.kubevirt.ui/parent-support-level: Community
    openshift.io/display-name: Virtual ROSE Template
  labels:
    os.template.kubevirt.io/centos8: "true"
    template.kubevirt.io/type: vm
    vm.kubevirt.io/template: rose-vm-template
    vm.kubevirt.io/template.namespace: vr2-fall2021-virtualrose2021
    workload.template.kubevirt.io/desktop: "true"
  name: rose-vm-template
  namespace: vr2-fall2021-virtualrose2021
objects:
- apiVersion: kubevirt.io/v1
  kind: VirtualMachine
  metadata:
    annotations:
      vm.kubevirt.io/validations: |
        [
          {
            "name": "minimal-required-memory",
            "path": "jsonpath::.spec.domain.resources.requests.memory",
            "rule": "integer",
            "message": "This VM requires more memory.",
            "min": 1610612736
          }
        ]
    labels:
      app: ${NAME}
      vm.kubevirt.io/template: rose-vm-template
    name: ${NAME}
  spec:
    dataVolumeTemplates:
    - metadata:
        name: ${NAME}-rootdisk
        namespace: vr2-fall2021-virtualrose2021
      spec:
        pvc:
          accessModes:
            - ReadWriteMany
          resources:
            requests:
              storage: 25Gi
          storageClassName: ocs-external-storagecluster-ceph-rbd
          volumeMode: Block
        source:
          pvc:
            name: centos-8.4
            namespace: openshift-virtualization-os-images
    - metadata:
        name: ${NAME}-disk-0
        namespace: vr2-fall2021-virtualrose2021
      spec:
        pvc:
          accessModes:
            - ReadWriteMany
          resources:
            requests:
              storage: 25Gi
          storageClassName: ocs-external-storagecluster-ceph-rbd
          volumeMode: Block
        source:
          blank: {}
    running: false
    template:
      metadata:
        annotations:
          vm.kubevirt.io/os: centos8
        labels:
          kubevirt.io/domain: ${NAME}
      spec:
        accessCredentials:
          - sshPublicKey:
              source:
                secret:
                  secretName: authorizedsshkeys-${NAME}
              propagationMethod:
                configDrive: {}
        domain:
          cpu:
            cores: 4
            sockets: 1
            threads: 1
          devices:
            disks:
            - disk:
                bus: virtio
              name: cloudinitdisk
            - bootOrder: 1
              disk:
                bus: virtio
              name: rootdisk
            - disk:
                bus: virtio
              name: disk-0
            inputs:
            - bus: virtio
              name: tablet
              type: tablet
            interfaces:
            - masquerade: {}
              model: virtio
              name: default
            networkInterfaceMultiqueue: true
            rng: {}
          machine:
            type: pc-q35-rhel8.4.0
          resources:
            requests:
              cpu: 4
              memory: 8Gi
            limits:
              cpu: 4
              memory: 8Gi
        evictionStrategy: LiveMigrate
        hostname: ${NAME}
        networks:
        - name: default
          pod: {}
        terminationGracePeriodSeconds: 180
        volumes:
        - cloudInitConfigDrive:
            userData: |
              #cloud-config
          name: cloudinitdisk
        - dataVolume:
            name: ${NAME}-rootdisk
          name: rootdisk
        - dataVolume:
            name: ${NAME}-disk-0
          name: disk-0
parameters:
- description: Name for the new VM
  name: NAME
  required: true
