apiVersion: template.openshift.io/v1
kind: Template
metadata:
  name: rose-integrated-template
  namespace: summer2022-virtualrose
objects:
  - apiVersion: v1
    kind: Secret
    metadata:
      name: userdata-${NAME}
    type: Opaque
    stringData:
      userdata: |
        #cloud-config
        user: fedora
        password: ${CLOUD_USER_PASSWORD}
        chpasswd:
          expire: false
        ssh_authorized_keys:
          - >-
            ssh-rsa
            AAAAB3NzaC1yc2EAAAADAQABAAACAQDHU+dRblINH9VOKWKluyyE1xz0GG6YMIiTCgUlDrEzvybC0Y0luIj87rQFHmihYFrmYdrCe2v2dFo1LggJEMPh3jfrXzJVl7KjbTOdsUSVwWCHD07uAiyNmH7aNGFuS4B6oiQj5NSTzl5C0Mvt/JIZmkky2305tZoF40bGlHP/U3tXoU+QPRqV44HR0AdkMArHADQoR/cpEQJantNuQsV2BouzfOJ8GcFLDU2ZPESgubrd4CxQ7p2+uujl0WsTsz0Ip3FkJINBHBnOGM9NteHVsiGJgmg3oeOhcH31bjYOToRNKvjAiepAsQMjhfm3GE850DcFJO6kEGD8umbhRiXZIfGJkqw1HWzcaN09q9cOWczMUytGBy6BGc7eNdf03F9FHLOO8c5gcA6Sd7rJFZD6LbRv+O8mtbLpL9Bi41I/5vNgNo0HI0Z2w56r9F8rRQ+jy4HR29hvV5yR7LZHC2kJ3TZiZBeqy5UG6SlQI4fOq1JHQ9/IzT4wV+sxQz38k3Yir6RE/Yg9N8wTMxpYG5/LsXa/eGRThCRbbaY5IgSK4NAWDDhMEt9TqTwrNSzEMi6Xv5DLROtyctUNN5fcN2M+evcJ4GqUgaw87e6Jk89cyQj/f3XLRjO2Yxudl5uLDd4f5aOnMJxsr8+3j5xMe8BNM9VkZqhPM/FEhi40xAl9lQ==
            lars@redhat.com
          - >-
            ssh-rsa
            AAAAB3NzaC1yc2EAAAADAQABAAABgQC01DutJQ022PzD8lKeAgwZSEu++moUOgZb/G08e8x1WQYepAGeW1wAaA7QzpmqAS/Py0z3vkDtGVUAlfs1FMyiP8bQMPRqgYzXtCfP8N/VQZWyWcsZaVxx3i3Y0gQUpnWjNevDw0a6ldwoqlgvIsCqNavnjLlZoHq49g0hJ/G8h0m9zjcWNWvTGzgc8Wm6AvdLPgsnKyXbnJl9M7oIaufw0EfODQiuLtBsMuQgBgJvqP9izqldCl6SeqfOkiaMbs3MCp4LwRUTEId1QF+JZOu6/DguIFaPj8uJHYcsqTICc0+7IJquwerj0KIAPfUvP+aXrqDaUI3hNn2V6aW52N8eAoWf3ejDHdFjK3p205glcXBQVLaNACzDfAYwLIKXVqa4oRrUoj33WgPn1s2KxuFOQaYlzLwP+7+k5mbdtXs1BEF4jiCuyskhN8SFk+g0wBonVICmAck/Qk2lV+Mw6MBzd720jCJTMmeftg41E5CK0LHxhlSyJ71KvpxxTVxRlVE=
            guypazbenitzhak@gpazbeni-mac
          - ${SSHKEY}
  - apiVersion: v1
    kind: Service
    metadata:
      name: ${NAME}-vm-service
      labels:
        kubevirt.io/domain: ${NAME}
    spec:
      ports:
        - name: ssh
          port: 22
        - name: http
          port: 80
        - name: https
          port: 443
        - name: rdp
          port: 3389
        - name: rdp-alt
          targetPort: 3389
          port: 3390
      selector:
        kubevirt.io/domain: ${NAME}
      type: LoadBalancer
  - apiVersion: kubevirt.io/v1
    kind: VirtualMachine
    metadata:
      annotations:
        massopen.cloud/password: ${CLOUD_USER_PASSWORD}
        vm.kubevirt.io/validations: |
          [
            {
              "name": "minimal-required-memory",
              "path": "jsonpath::.spec.domain.resources.requests.memory",
              "rule": "integer",
              "message": "This VM requires more memory.",
              "min": 1610612736
            }
          ]
      labels:
        kubevirt.io/domain: ${NAME}
        vm.kubevirt.io/template: rose-integrated-template
      name: ${NAME}-vm
    spec:
      dataVolumeTemplates:
        - metadata:
            name: ${NAME}-rootdisk
            namespace: summer2022-virtualrose
          spec:
            pvc:
              accessModes:
                - ReadWriteMany
              resources:
                requests:
                  storage: 25Gi
              storageClassName: ocs-external-storagecluster-ceph-rbd
              volumeMode: Block
            source:
              pvc:
                name: virtual-rose-fedora-36
                namespace: summer2022-virtualrose
      running: true
      template:
        metadata:
          annotations:
            vm.kubevirt.io/os: fedora36
          labels:
            kubevirt.io/domain: ${NAME}
        spec:
          domain:
            cpu:
              cores: 4
              sockets: 1
              threads: 1
            devices:
              disks:
                - disk:
                    bus: virtio
                  name: cloudinitdisk
                - bootOrder: 1
                  disk:
                    bus: virtio
                  name: rootdisk
              inputs:
                - bus: virtio
                  name: tablet
                  type: tablet
              interfaces:
                - masquerade: {}
                  model: virtio
                  name: default
              networkInterfaceMultiqueue: true
              rng: {}
            machine:
              type: pc-q35-rhel8.4.0
            resources:
              requests:
                cpu: 4
                memory: 8Gi
              limits:
                cpu: 4
                memory: 8Gi
          evictionStrategy: LiveMigrate
          hostname: ${NAME}
          networks:
            - name: default
              pod: {}
          terminationGracePeriodSeconds: 180
          volumes:
            - cloudInitConfigDrive:
                secretRef:
                  name: userdata-${NAME}
              name: cloudinitdisk
            - dataVolume:
                name: ${NAME}-rootdisk
              name: rootdisk
parameters:
  - description: Name for the new VM
    name: NAME
    required: true
  - description: Student SSH key
    name: SSHKEY
    required: true
  - description: Randomized password for the cloud-init user centos
    from: '[a-z0-9]{4}-[a-z0-9]{4}-[a-z0-9]{4}'
    generate: expression
    name: CLOUD_USER_PASSWORD
