apiVersion: template.openshift.io/v1
kind: Template
metadata:
  annotations:
    iconClass: icon-centos
    name.os.template.kubevirt.io/centos8: CentOS 8 or higher
    template.kubevirt.io/provider: Red Hat Virtusl ROSE
    template.kubevirt.ui/parent-provider: Red Hat
    template.kubevirt.ui/parent-provider-url: https://www.centos.org
    template.kubevirt.ui/parent-support-level: Community
  labels:
    os.template.kubevirt.io/centos8: "true"
    template.kubevirt.io/type: vm
    vm.kubevirt.io/template: vm-rose-template
    vm.kubevirt.io/template.namespace: vr2-fall2021-virtualrose2021
    workload.template.kubevirt.io/desktop: "true"
  name: vm-rose-template
  namespace: vr2-fall2021-virtualrose2021
objects:
- apiVersion: kubevirt.io/v1
  kind: VirtualMachine
  metadata:
    annotations:
      vm.kubevirt.io/validations: |
        [
          {
            "name": "minimal-required-memory",
            "path": "jsonpath::.spec.domain.resources.requests.memory",
            "rule": "integer",
            "message": "This VM requires more memory.",
            "min": 1610612736
          }
        ]
    labels:
      app: ${NAME}
      vm.kubevirt.io/template: vm-rose-template
    name: ${NAME}
  spec:
    dataVolumeTemplates:
    - metadata:
        name: ${NAME}-rootdisk
        namespace: vr2-fall2021-virtualrose2021
      spec:
        pvc:
          accessModes:
            - ReadWriteMany
          resources:
            requests:
              storage: 25Gi
          storageClassName: ocs-external-storagecluster-ceph-rbd
          volumeMode: Block
        source:
          pvc:
            name: centos-8.4
            namespace: openshift-virtualization-os-images
    - metadata:
        name: ${NAME}-disk-0
        namespace: vr2-fall2021-virtualrose2021
      spec:
        pvc:
          accessModes:
            - ReadWriteMany
          resources:
            requests:
              storage: 25Gi
          storageClassName: ocs-external-storagecluster-ceph-rbd
          volumeMode: Block
        source:
          blank: {}
    running: false
    template:
      metadata:
        annotations:
          vm.kubevirt.io/os: centos8
        labels:
          kubevirt.io/domain: ${NAME}
      spec:
        domain:
          cpu:
            cores: 4
            sockets: 1
            threads: 1
          devices:
            disks:
            - disk:
                bus: virtio
              name: cloudinitdisk
            - bootOrder: 1
              cdrom:
                bus: sata
              name: rootdisk
            - disk:
                bus: virtio
              name: disk-0
            inputs:
            - bus: virtio
              name: tablet
              type: tablet
            interfaces:
            - masquerade: {}
              model: virtio
              name: default
            networkInterfaceMultiqueue: true
            rng: {}
          machine:
            type: pc-q35-rhel8.4.0
          resources:
            requests:
              memory: 8Gi
        evictionStrategy: LiveMigrate
        hostname: ${NAME}
        networks:
        - name: default
          pod: {}
        terminationGracePeriodSeconds: 180
        volumes:
        - cloudInitNoCloud:
            userData: |
              user: centos
              password: centos
              chpasswd:
                expire: false
              ssh_authorized_keys:
                - >-
                  ssh-rsa
                  AAAAB3NzaC1yc2EAAAADAQABAAABgQC9hLzJmRsL6h4mzJyPS4Z1JnNe1VOYf7rs3tWN/Z5P5hKW3trA4gTlEGDckj1FqTkBbSyWgysiPUeQgGb7OAdCyPIaHGPysCBWLRWl/LjrRsNbENcMeY/svRzkHww70x1FkZ23oDw4yk1Km7PmBqaJa8VpDsWGt4z7Em1ud7fSFVmH6UlQg08RJXeZmJIlwwmJkBso0IytbWK8MiV2OzeonCYISBejBpsocAS+7PtdAQ7NQOW+bqzVsyZHaaiDJun3aTMCirFlHbSJANxuvcGyyx43crUBcyXgPwXACKpYSik11tJgbno3JYY039jxUNapBdWGZpCIcX9tbVodYknxjGCB8INdad7LVAACVxP2PrhBrgoRs2y85/8FwIaZPeO+IunCxr9T+2AIivwC6Tk8bHXEoNiteZCBRmSMF/f5l793u59WkuE4F4JizmCnT9/n9Z9aAYkyHna7yQ6MQ481o3JJg/T12qhXyJQmMEdtie2UrR1GWvJ7MsVXaYQciWs=
                  sleviim@sleviim.redhat
                - >-
                  ssh-rsa
                  AAAAB3NzaC1yc2EAAAADAQABAAABgQDMxISEo+fmk1gL9uYuUJllKyks+2hXn9iSszUtKlNHvcEHzxhOa7pK+pjo5QGixET+TBaBGz7j7vX6zhbx44H0D1EnU5jvUjRZX4ysuOTlzUquoJ0ufm1y934smo6zO/JCpw3+kJgNs3xqthPNFXbqYCkHAqEjSU+qNgYSx2zK++4M21gHiyY8z4GXEyeQwqr65FHypHAAA6Tf4/mhH3bHT5A89xKcGBlJhfSkKPIeSaec+Vis18GYHQ9QGg442j9Okjhnb2V7oYyajQ+vIv7UUWTcdoRWSPFbW0wOfKw2100sPIGL6dV+gQg4rCJ2E5Rq/KawKP2XDI24mAs7HeBjXZFg8rjwsPWTJ4IkNegSlS5G2kb0tfow9PJVXcVhlPhrhyiIUoTLx9wUx4yMp2Tu1VeZptrWCMRXyJvW88Faj4YOmAlocEyXGVoms2pH+CywGD3FG4GmYy6+VyvmTT/1Bnp+fdpy1nw4+Q9Ude25lgXy2/077Fx3UobKNMKW/X0=
                  speretz@speretz.tlv.csb
              hostname: vm-template
          name: cloudinitdisk
        - dataVolume:
            name: ${NAME}-rootdisk
          name: rootdisk
        - dataVolume:
            name: ${NAME}-disk-0
          name: disk-0
parameters:
- description: Name for the new VM
  name: NAME
  required: true
- description: Randomized password for the cloud-init user
  from: '[a-z0-9]{4}-[a-z0-9]{4}-[a-z0-9]{4}'
  generate: expression
  name: CLOUD_USER_PASSWORD
